### ISSUE TITLE
Charades_v1_features_flow is no longer available in Charades

### ISSUE THREAD

**Issue by paloma-jim** [maups/charades_stuff#2]
Hi,

It seems wget http://ai2-website.s3.amazonaws.com/data/Charades_v1_features_flow.tar.gz is no longer available. Does it correspond to https://ai2-public-datasets.s3-us-west-2.amazonaws.com/charades/**Charades_v1_flow.tar**?

I downloaded this part corresponding to the optical flow however when running the create_helper_files.cpp i also faced the segmentation fault indicated in the post before. Then, I took the helper_file folder you included in that issue but i realized that each folder, e.g. train_0.txt contains somethin like charades_v1_features_flow/I8QJN/I8QJN-000165.txt, however, what i see in the new Charades_v1_flow is x.jpg optical flow files (x is either x or y depending on the optical flow direction) but any .txt file.

Is this ok? Is it possible i got wrong when taking the optical flow part from the charades dataset - https://prior.allenai.org/projects/charades????

**Comment by maups** [comment]
You are downloading the optical flow frames, but this code uses the features extracted from these frames instead. The correct link is this one: https://ai2-public-datasets.s3-us-west-2.amazonaws.com/charades/Charades_v1_features_flow.tar.gz

I'll update the README file with this new link.

**Comment by paloma-jim** [comment]
Yes, i realized later. Thank you Mauricio for the quick answer
